# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16105623534ed87105213c1ca131800a4492ee5e8a428dd3a3b5de5869fb10824de5e98d269bf187af026877842d331becf1e7df2f6dd66ce2a86f57ed89a29b

test:
  secret_key_base: 0917c890a3084d5ed40b089e1cccdba67a37f48cb11085d0d82fc32b3c7da15f7fd33c53da5337f8ec585e992109fba56f5687195ab7370d0d415d6a21d32022

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
